# Config Postgres Pod
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prod-pg
spec:
  serviceName: prod-pg
  selector:
    matchLabels:
      app: ecommerce
      tier: postgres
  template:
    metadata:
      labels:
        app: ecommerce
        tier: postgres
    spec:
      containers:
      - name: prod-pg
        image: postgres:latest
        envFrom:
          - configMapRef:
              name: postgres-config
        ports:
        - containerPort: 5432
          name: postgredb
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 2Gi
# Config Service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: ecommerce
    tier: postgres
data:
  POSTGRES_DB: product
  POSTGRES_USER: product_robot
  POSTGRES_PASSWORD: pr0dr0b0t
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: prod-pg
  labels:
    app: ecommerce
    tier: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
    app: ecommerce
    tier: postgres
# Config PersistentVolume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-pg
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.2.15
    path: /home/prod-pg
