# Config Stage Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-pod
  labels:
    app: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
    # Config Containers
      containers:
      - name: frontend
        image: nginx:1.22.0
        ports:
        - containerPort: 80
      - name: backend
        image: debian
        command: ["sleep", "3600"]
---
# Config Service
apiVersion: v1
kind: Service
metadata:
  name: web-dev
  labels:
    app: web
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: web
